### ISSUE TITLE
[Bug]: Connecting to party media server broken

### ISSUE THREAD

**Issue by barankyle** [EtherealEngine/etherealengine#7664]
When I create a party, some errors occur client-side that eventually cause all of the UI to disappear:

```
Error: Cannot read properties of undefined (reading 'party_users')
    at Object.dispatchNotify (NotificationService.ts:23:20)
    at Object.createParty (PartyService.ts:160:27)
```

```
ActionFunctions.ts:405 TypeError: Cannot read properties of undefined (reading 'value')
    at ChatService.ts:124:43
```

```
receiveJoinMediaServer.ts:12 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'peerID')
    at receiveJoinMediaServer (receiveJoinMediaServer.ts:12:45)
    at onConnectToInstance (SocketWebRTCClientFunctions.ts:151:8)
```

```
Uncaught (in promise) TypeError: Cannot destructure property 'id' of 'undefined' as it is undefined.
    at Device.createRecvTransport (Device.js:340:27)
    at createTransport (SocketWebRTCClientFunctions.ts:423:71)
    at async initReceiveTransport (SocketWebRTCClientFunctions.ts:574:27)
```

```
SystemFunctions.tsx:84 Failed to execute system UpdateNearbyUsersSystem
  | (anonymous) | @ | SystemFunctions.tsx:84
```

```
TypeError: s?.request is not a function
    at updateNearbyAvatars (UpdateNearbyUsersSystem.ts:23:12)
    at Object.execute (UpdateNearbyUsersSystem.ts:46:27)
```

```
TypeError: Cannot read properties of undefined (reading 'value')
    at NetworkInstanceProvisioning.tsx:142:43
    at Zo (react-dom.production.min.js:244:332)
```

**Comment by HexaField** [comment]
These have all been addressed in recent PRs.
