### ISSUE TITLE
[Bug]: projectPermission resolver does not work properly

### ISSUE THREAD

**Issue by barankyle** [EtherealEngine/etherealengine#8760]
I noticed that projectPermissions were not being returned on projects. The issue appears to be that they are only populated in the resolver when context.params.query.allowed is true, but we delete context.params.query.allowed if it's there in project.class.ts:find, since that's not a queryable column.

When I set params.allowed to true to try to get around that, and made the check in the projectResolver `if (context.params?.allowed)`, I was getting this error (got this output from adding a try/catch around the projectPermission.find in that resolver): 

```
Error: Undefined binding(s) detected when compiling SELECT. Undefined column(s): [userId] query: select `project-permission`.* from `project-permission` where `projectId` = ? and `userId` = ? limit ?
      at QueryCompiler_MySQL.toSQL (/home/kyle/Development/Forks/etherealengine/node_modules/knex/lib/query/querycompiler.js:110:13)
      at Builder.toSQL (/home/kyle/Development/Forks/etherealengine/node_modules/knex/lib/query/querybuilder.js:83:44)
      at ensureConnectionCallback (/home/kyle/Development/Forks/etherealengine/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)
      at Runner.ensureConnection (/home/kyle/Development/Forks/etherealengine/node_modules/knex/lib/execution/runner.js:300:20)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Runner.run (/home/kyle/Development/Forks/etherealengine/node_modules/knex/lib/execution/runner.js:30:19)
      at async ProjectPermissionService._find (/home/kyle/Development/Forks/etherealengine/node_modules/@feathersjs/knex/src/adapter.ts:188:46)
      at async ProjectPermissionService.find (/home/kyle/Development/Forks/etherealengine/packages/server-core/src/projects/project-permission/project-permission.class.ts:93:33)
```

**Comment by barankyle** [comment]
Seems to have been resolved at some point.
